local colours = {
	"horizon",
	"moonlight",
	"kanagawa-wave",
	"kanagawa-dragon",
	"kanagawa-lotus",
	"rose-pine-main",
	"rose-pine-moon",
	"rose-pine-dawn",
	"catppuccin-mocha",
	"catppuccin-macchiato",
	"catppuccin-frappe",
	"catppuccin-latte",
	"monokai-pro-classic",
	"monokai-pro-default",
	"monokai-pro-machine",
	"monokai-pro-octagon",
	"monokai-pro-spectrum",
	"monokai-pro-ristretto",
	"material-darker",
	"material-lighter",
	"material-oceanic",
	"material-palenight",
	"material-deep ocean",
}

vim.cmd.colorscheme(colours[1] or "habamax")
